<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partidos [
    <!ELEMENT partidos (partido)+>
    <!ELEMENT partido (nombrelocal, nombrevisitante)>
    <!ELEMENT nombrelocal (#PCDATA)>
    <!ELEMENT nombrevisitante (#PCDATA)>
    <!ATTLIST nombrelocal goles CDATA #REQUIRED>
    <!ATTLIST nombrevisitante goles CDATA #REQUIRED>
]>

<partidos>
    <partido>
        <nombrelocal goles="0">Nottingham Presa</nombrelocal>
        <nombrevisitante goles="1">Inter de Mitente</nombrevisitante>
    </partido>

    <partido>
        <nombrelocal goles="3">Vodka Juniors</nombrelocal>
        <nombrevisitante goles="3">Sparta da Risa</nombrevisitante>
    </partido>

    <partido>
        <nombrelocal goles="4">Water de MÃºnich</nombrelocal>
        <nombrevisitante goles="2">Esteaua es del grifo</nombrevisitante>
    </partido>
</partidos>