=== rafacab1/1daw-xml-lm/abril2020/dia27examen/ejercicio2xsd/curriculums.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="curriculums">
  <xs:complexType>
     <xs:sequence>
      <xs:element name="cv" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="datos_personales" minOccurs="1" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="nombre" type="xs:string"/>
                  <xs:element name="apellido1" type="xs:string"/>
                  <xs:element name="apellido2" type="xs:string"/>
                  <xs:element name="telefono" type="xs:integer"/>
                  <xs:element name="correo" type="xs:string"/>
                  <xs:element name="direcciones">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="direccion" maxOccurs="2">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="calle" type="xs:string"/>
                              <xs:element name="localidad" type="xs:string" default="Córdoba"/>
                              <xs:element name="codigopostal" type="xs:integer">
                              </xs:element>
                              <xs:element name="provincia" type="xs:string" default="Córdoba"/>
                              <xs:element name="pais" type="xs:string"/>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="rrss" maxOccurs="5">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="nick" type="xs:string"/>
                        <xs:element name="enlace" type="xs:string"/>
                        <xs:element name="valoracion" minOccurs="0">
                          <xs:simpleType>
                            <xs:restriction base="xs:integer">
                              <xs:minInclusive value="1"/>
                              <xs:maxInclusive value="5"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="datos_academicos" minOccurs="1" maxOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="titulaciones_oficiales">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="descripcion" type="xs:string"/>
                      <xs:element name="organismo" type="xs:string"/>
                      <xs:element name="fechaInicio" type="xs:date"/>
                      <xs:element name="fechaFinalizacion " type="xs:date"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="cursos">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="descripcion" type="xs:string"/>
                      <xs:element name="empresa" type="xs:string"/>
                      <xs:element name="fechaInicio" type="xs:date"/>
                      <xs:element name="fechaFinalizacion " type="xs:date"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="nivelIdioma">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="comprender" type="marcoEuropeo"/>
                      <xs:element name="hablar" type="marcoEuropeo"/>
                      <xs:element name="escribir" type="marcoEuropeo"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
            </xs:element>
            <xs:element name="experiencia_laboral" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="empresa">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="fechaInicio" type="xs:date"/>
                        <xs:element name="fechaFinalizacion" type="xs:date"/>
                        <xs:element name="tarea" type="xs:string" maxOccurs="unbounded"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attributeGroup ref="attcv"/>
        </xs:complexType>
      </xs:element>
     </xs:sequence> 
  </xs:complexType>
</xs:element>

<xs:attributeGroup name="attcv">
  <xs:attribute name="id" type="xs:ID" use="required"/>
  <xs:attribute name="fecha" type="xs:date" use="required"/>
  <xs:attribute name="categoria" type="xs:string" default="Desarrollador"/>
</xs:attributeGroup>

<xs:simpleType name="marcoEuropeo">
  <xs:restriction base="xs:string">
    <xs:enumeration value="A1"/>
    <xs:enumeration value="A2"/>
    <xs:enumeration value="B1"/>
    <xs:enumeration value="B2"/>
    <xs:enumeration value="C1"/>
    <xs:enumeration value="C2"/>
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== rafacab1/1daw-xml-lm/abril2020/dia27examen/ejercicio2xsd/curriculums.xml
<?xml version="1.0" encoding="UTF-8"?>
<curriculums xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="curriculums.xsd">

    <cv id="D1" fecha="2020-04-27" categoria="Desarrollador">
    <datos_personales>
      <nombre>Rafa</nombre>
      <apellido1>Caballero</apellido1>
      <apellido2>Osuna</apellido2>
      <telefono>957123321</telefono>
      <correo>rafacab@dominio.com</correo>
      <direcciones>
        <direccion>
          <calle>Falsa</calle>
          <localidad>Córdoba</localidad>
          <codigopostal>14014</codigopostal>
          <provincia>Córdoba</provincia>
          <pais>España</pais>
        </direccion>
      </direcciones>
      <rrss>
        <nombre>Twitter</nombre>
        <nick>rafacab1</nick>
        <enlace>twitter.com</enlace>
        <valoracion>3</valoracion>
      </rrss>
    </datos_personales>
    <datos_academicos>
      <titulaciones_oficiales>
        <descripcion>CFGM Sistemas Microinformáticos y Redes</descripcion>
        <organismo>Junta de Andalucía</organismo>
        <fechaInicio>2017-09-15</fechaInicio>
        <fechaFinalizacion>2019-05-13</fechaFinalizacion>
      </titulaciones_oficiales>
      <cursos>
        <descripcion>Curso prevención riesgos laborales</descripcion>
        <empresa>No Mas Golpes</empresa>
        <fechaInicio>2019-04-27</fechaInicio>
        <fechaFinalizacion>2019-04-29</fechaFinalizacion>
      </cursos>
      <nivelIdioma>
        <comprender>B1</comprender>
        <hablar>A1</hablar>
        <escribir>A2</escribir>
      </nivelIdioma>
    </datos_academicos>
    <experiencia_laboral>
      <empresa>
        <nombre>Empresita de Empresas</nombre>
        <fechaInicio>2019-03-13</fechaInicio>
        <fechaFinalizacion>2019-06-15</fechaFinalizacion>
        <tarea>Hace cosas y eso</tarea>
      </empresa>
    </experiencia_laboral>
    </cv>

    <cv id="D2" fecha="2020-04-27" categoria="Desarrollador">
    <datos_personales>
      <nombre>Rafa</nombre>
      <apellido1>Caballero</apellido1>
      <apellido2>Osuna</apellido2>
      <telefono>957123321</telefono>
      <correo>rafacab@dominio.com</correo>
      <direcciones>
        <direccion>
          <calle>Falsa</calle>
          <localidad>Córdoba</localidad>
          <codigopostal>14014</codigopostal>
          <provincia>Córdoba</provincia>
          <pais>España</pais>
        </direccion>
      </direcciones>
      <rrss>
        <nombre>Twitter</nombre>
        <nick>rafacab1</nick>
        <enlace>twitter.com</enlace>
        <valoracion>3</valoracion>
      </rrss>
    </datos_personales>
    <datos_academicos>
      <titulaciones_oficiales>
        <descripcion>CFGM Sistemas Microinformáticos y Redes</descripcion>
        <organismo>Junta de Andalucía</organismo>
        <fechaInicio>2017-09-15</fechaInicio>
        <fechaFinalizacion>2019-05-13</fechaFinalizacion>
      </titulaciones_oficiales>
      <cursos>
        <descripcion>Curso prevención riesgos laborales</descripcion>
        <empresa>No Mas Golpes</empresa>
        <fechaInicio>2019-04-27</fechaInicio>
        <fechaFinalizacion>2019-04-29</fechaFinalizacion>
      </cursos>
      <nivelIdioma>
        <comprender>B1</comprender>
        <hablar>A1</hablar>
        <escribir>A2</escribir>
      </nivelIdioma>
    </datos_academicos>
    <experiencia_laboral>
      <empresa>
        <nombre>Empresita de Empresas</nombre>
        <fechaInicio>2019-03-13</fechaInicio>
        <fechaFinalizacion>2019-06-15</fechaFinalizacion>
        <tarea>Hace cosas y eso</tarea>
      </empresa>
    </experiencia_laboral>
    </cv>

</curriculums>
